/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000",
    NEXT_PUBLIC_STELLAR_NETWORK: process.env.NEXT_PUBLIC_STELLAR_NETWORK || "testnet",
    NEXT_PUBLIC_CONTRACT_AID_PROVENANCE: process.env.NEXT_PUBLIC_CONTRACT_AID_PROVENANCE || "",
    NEXT_PUBLIC_CONTRACT_DONATION_VAULT: process.env.NEXT_PUBLIC_CONTRACT_DONATION_VAULT || "",
    NEXT_PUBLIC_CONTRACT_BENEFICIARY_REGISTRY: process.env.NEXT_PUBLIC_CONTRACT_BENEFICIARY_REGISTRY || "",
    NEXT_PUBLIC_LINGAP_RECEIVER_PUBLIC_KEY: process.env.NEXT_PUBLIC_LINGAP_RECEIVER_PUBLIC_KEY || "",
  },
};

export default nextConfig;
